name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.run_id }}"
          echo "${{github.repository}}"
          echo "${{github.repository_owner}}"
          echo "${{github.event}}"
