name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.run_id }}"
          echo "${{github.action}}"
          echo "${{github.action_path}}"
          echo "${{github.action_ref}}"
          echo "${{github.action_repository}}"
          echo "${{github.action_status}}"
          echo "${{github.actor_id}}"
          echo "${{github.api_url}}"
          echo "${{github.base_ref}}"
