name: intermediate-environment-variables
on:
  push:
    branches:
      - "feature"
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME}}
    steps:
      - run: echo "${USERNAME}"
