name: Validate PR Title

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1 # 最新のコミットのみを取得

      - name: Validate PR Title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Validating PR title..."
          PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
          echo "PR Title: $PR_TITLE"
          
          if [[ ! "$PR_TITLE" =~ ^(JREIT-[0-9]+|ReitDB-[0-9]+) ]]; then
            echo "Invalid PR title format. Closing the PR."
            curl -X PATCH \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
              -d '{"state":"closed"}'
          else
            echo "PR title is valid."
          fi
